Trait {
	#name : #EDASPortSettingsPort,
	#traits : 'EDASSettingsPort',
	#classTraits : 'EDASSettingsPort classTrait',
	#category : #'EDAS-Settings-Ports'
}

{ #category : #testing }
EDASPortSettingsPort >> commandListenerSettingsAdapterClass [
	self shouldBeImplemented
]

{ #category : #testing }
EDASPortSettingsPort >> commandListenerSettingsAdapterClass: aClass [

	self shouldBeImplemented
]

{ #category : #testing }
EDASPortSettingsPort >> environmentSettingsAdapterClass [

	self shouldBeImplemented
]

{ #category : #accessing }
EDASPortSettingsPort >> environmentSettingsAdapterClass: aClass [

	self shouldBeImplemented
]
