Trait {
	#name : #EDASPortSettingsPort,
	#traits : 'EDASSettingsPort',
	#classTraits : 'EDASSettingsPort classTrait',
	#category : #'EDAS-Settings-Ports'
}

{ #category : #accessing }
EDASPortSettingsPort >> adapterClassAccessor [

	self shouldBeImplemented
]

{ #category : #accessing }
EDASPortSettingsPort >> adapters [

	self shouldBeImplemented
]

{ #category : #testing }
EDASPortSettingsPort >> commandListenerSettings [

	self shouldBeImplemented
]

{ #category : #testing }
EDASPortSettingsPort >> commandListenerSettings: anObject [

	self shouldBeImplemented
]

{ #category : #testing }
EDASPortSettingsPort >> commandListenerSettingsAdapterClass [

	self shouldBeImplemented
]

{ #category : #testing }
EDASPortSettingsPort >> commandListenerSettingsAdapterClass: aClass [

	self shouldBeImplemented
]

{ #category : #testing }
EDASPortSettingsPort >> environmentSettings [

	self shouldBeImplemented
]

{ #category : #accessing }
EDASPortSettingsPort >> environmentSettings: anObject [

	self shouldBeImplemented
]

{ #category : #testing }
EDASPortSettingsPort >> eventPublisherSettingsAdapterClass [

	self shouldBeImplemented
]

{ #category : #testing }
EDASPortSettingsPort >> eventPublisherSettingsAdapterClass: aClass [

	self shouldBeImplemented
]
